# Generated by Django 4.1.3 on 2022-11-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=280)),
                ('en_name', models.CharField(max_length=280)),
                ('alt_name', models.CharField(max_length=280)),
                ('description', models.CharField(max_length=1000)),
                ('tags', models.ManyToManyField(to='myapi.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('cost', models.IntegerField()),
                ('number', models.CharField(max_length=60)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.title')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('view_counter', models.IntegerField()),
                ('likes_counter', models.IntegerField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.volume')),
            ],
        ),
    ]
