# Generated by Django 4.1.3 on 2022-11-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='likes_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
