# Generated by Django 4.1.3 on 2022-11-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_chapter_likes_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_volume', to='myapi.title'),
        ),
    ]
